language: java
jdk:
  - oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install: ./gradlew :application:dependencies
install: ./gradlew -i :application:assemble
script: ./gradlew -i :application:test

